#ifndef _VIV_NUMBER_CLASS_H_
#define _VIV_NUMBER_CLASS_H_

#define TOTAL_PIXELS 16
#define PIXEL_THRESHOLD 1

#define TOP 0x01
#define MIDDLE 0x02
#define BOTTOM 0x04
#define TOP_LEFT 0x08
#define TOP_RIGHT 0x10
#define BOTTOM_LEFT 0x20
#define BOTTOM_RIGHT 0x40

#define ZERO_SEGMENTS ( TOP | BOTTOM | TOP_LEFT | TOP_RIGHT | BOTTOM_LEFT | BOTTOM_RIGHT )
#define ONE_SEGMENTS_LEFT ( TOP_LEFT | BOTTOM_LEFT )
#define ONE_SEGMENTS_RIGHT ( TOP_RIGHT | BOTTOM_RIGHT )
#define TWO_SEGMENTS ( TOP | TOP_RIGHT | MIDDLE | BOTTOM_LEFT | BOTTOM )
#define THREE_SEGMENTS ( TOP | MIDDLE | BOTTOM | TOP_RIGHT | BOTTOM_RIGHT )
#define FOUR_SEGMENTS ( TOP_LEFT | TOP_RIGHT | MIDDLE | BOTTOM_RIGHT )
#define FOUR_SEGMENTS_ERR ( FOUR_SEGMENTS | BOTTOM_LEFT )
#define FIVE_SEGMENTS ( TOP | TOP_LEFT | MIDDLE | BOTTOM_RIGHT | BOTTOM )
#define SIX_SEGMENTS_PARTIAL ( TOP_LEFT | MIDDLE | BOTTOM_LEFT | BOTTOM_RIGHT | BOTTOM )
#define SIX_SEGMENTS ( TOP | SIX_SEGMENTS_PARTIAL )
#define SEVEN_SEGMENTS ( TOP | TOP_RIGHT | BOTTOM_RIGHT )
#define EIGHT_SEGMENTS ( TOP | MIDDLE | BOTTOM | TOP_LEFT | TOP_RIGHT | BOTTOM_LEFT | BOTTOM_RIGHT )
#define NINE_SEGMENTS ( TOP | TOP_LEFT | TOP_RIGHT | MIDDLE | BOTTOM_RIGHT | BOTTOM )
#define NINE_SEGMENTS_PARTIAL ( TOP | TOP_LEFT | TOP_RIGHT | MIDDLE | BOTTOM_RIGHT )

#endif // _NUMBER_CLASS_H_
